name: Checkout

on:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: pae26/checkout-test-2
          path: checkout-test-2
        run: echo "Success!"